.PHONY: my_world
my_world:
	roslaunch gazebo_ros empty_world.launch world_name:=/user/HS401/tl01159/Workspace/UoS-ros-setup/catkin_ws/src/lab5/worlds/lab5.world

.PHONY: launch_turtle
launch_turtle:
	roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch

.PHONY: launch_turtle_teleop
launch_turtle_teleop:
	roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch

.PHONY: launch_turtle_rviz
launch_turtle_rviz:
	roslaunch turtlebot3_gazebo turtlebot3_gazebo_rviz.launch
